### PR TITLE
Corrected Readme

### PR DESCRIPTION
**Pull request by gabsoftware**
I just corrected a minor mistake in the Readme.

### CODE REVIEW

**Comment by ivanvermeyen** [comment]
Thanks man! I configured my editor to use unix line endings now. ;)

**Comment by gabsoftware** [comment]
Well the correction was more about an occurence of "js" being replaced by "css" in In the `public/js` folder" ☺

**Comment by ivanvermeyen** [comment]
haha yes, but the line endings intrigued me :D

**Comment by gabsoftware** [comment]
Well, should I submit a new pull request? Maybe cleaner with only one commit? Because the readme is still showing "js" instead of "css" :-)

**Comment by ivanvermeyen** [comment]
Lol.  I'm sorry... I thought I merged it last time :) it should be merged now :) Thanks again!

**Comment by gabsoftware** [comment]
You're welcome :-) Wish I can contribute something more useful next time! It's really a great navigation bar.

**Pull request merged**
